"use client";

import { useMemo, useState } from "react";
import { Banknote, Check, CircleDollarSign, CreditCard, QrCode, ReceiptText, Split, WalletCards } from "lucide-react";
import { money } from "@/lib/utils";
import { useOperations } from "../operations-provider";
import { Button, Card, Modal, PageHeader, StatusBadge } from "../ui";

export function BillingView() {
  const { bills, addPayment, updateTableStatus } = useOperations();
  const [selectedId, setSelectedId] = useState(bills[0]?.id ?? 0);
  const [split, setSplit] = useState<"equal" | "products" | "custom">("equal");
  const [paymentOpen, setPaymentOpen] = useState(false);
  const [method, setMethod] = useState("Tarjeta");
  const selected = bills.find((bill) => bill.id === selectedId) ?? bills[0];
  const total = useMemo(() => selected.items.reduce((sum, item) => sum + item.price * item.quantity, 0), [selected]);
  const remaining = Math.max(0, total - selected.payments);
  const perPerson = remaining / selected.guests;
  function pay() { addPayment(selected.id, remaining); updateTableStatus(selected.table, "Limpieza"); setPaymentOpen(false); }
  return <div className="space-y-6"><PageHeader eyebrow="Caja" title="Cuentas abiertas" description="Dividí, combiná medios de pago y cerrá la mesa sin cálculos manuales." actions={<StatusBadge tone="success">Caja sincronizada</StatusBadge>} />
    <div className="grid gap-5 xl:grid-cols-[330px_1fr]">
      <Card className="h-fit overflow-hidden"><div className="border-b border-stone-100 p-4"><p className="text-xs font-semibold">Mesas con cuenta</p><p className="mt-1 text-[10px] text-stone-400">{bills.length} cuentas activas</p></div><div className="space-y-1 p-2">{bills.map((bill) => { const billTotal = bill.items.reduce((sum, item) => sum + item.price * item.quantity, 0); return <button key={bill.id} onClick={() => setSelectedId(bill.id)} className={`w-full rounded-2xl p-3.5 text-left transition ${selected.id === bill.id ? "bg-[#261d18] text-white" : "hover:bg-stone-50"}`}><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Mesa {bill.table}</p><p className={`mt-1 text-[9px] ${selected.id === bill.id ? "text-stone-400" : "text-stone-500"}`}>{bill.guests} personas · {bill.status}</p></div><p className="text-sm font-bold">{money(billTotal)}</p></div>{bill.payments > 0 && <div className="mt-3"><div className="h-1 overflow-hidden rounded-full bg-white/15"><div style={{ width: `${Math.min(100, (bill.payments / billTotal) * 100)}%` }} className="h-full bg-[#d39765]" /></div><p className={`mt-1 text-[9px] ${selected.id === bill.id ? "text-[#d7a77d]" : "text-stone-400"}`}>{money(bill.payments)} abonados</p></div>}</button>})}</div></Card>
      <div className="grid gap-5 lg:grid-cols-[1fr_330px]"><Card className="overflow-hidden"><div className="border-b border-stone-100 p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#9b6037]">Detalle de cuenta</p><h2 className="mt-1 font-serif text-3xl">Mesa {selected.table}</h2></div><ReceiptText size={24} className="text-stone-400" /></div></div><div className="p-5"><div className="space-y-4">{selected.items.map((item, index) => <div key={`${item.name}-${index}`} className="flex items-start gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-stone-100 text-[10px] font-bold">{item.quantity}</span><div className="flex-1"><p className="text-xs font-semibold">{item.name}</p><p className="mt-1 text-[10px] text-stone-400">{money(item.price)} c/u</p></div><p className="text-xs font-semibold">{money(item.price * item.quantity)}</p></div>)}</div><div className="my-5 h-px bg-stone-100" /><div className="space-y-2 text-xs"><div className="flex justify-between text-stone-500"><span>Subtotal</span><span>{money(total)}</span></div><div className="flex justify-between text-stone-500"><span>Pagado</span><span>− {money(selected.payments)}</span></div><div className="flex justify-between border-t border-stone-100 pt-3 text-base font-bold"><span>Saldo</span><span>{money(remaining)}</span></div></div></div></Card>
        <div className="space-y-4"><Card className="p-4"><div className="flex items-center gap-2"><Split size={16} className="text-[#9b6037]" /><h3 className="text-xs font-semibold">Dividir cuenta</h3></div><div className="mt-4 space-y-2">{[["equal", "Partes iguales", "Mismo monto por persona"], ["products", "Por productos", "Asignar cada consumo"], ["custom", "Personalizada", "Ingresar montos manuales"]].map(([id,title,detail]) => <button key={id} onClick={() => setSplit(id as typeof split)} className={`w-full rounded-xl border p-3 text-left transition ${split === id ? "border-[#b77843] bg-[#f6ebe1]" : "border-stone-200 bg-white"}`}><div className="flex items-center"><span className={`mr-3 flex h-4 w-4 items-center justify-center rounded-full border ${split === id ? "border-[#9b6037] bg-[#9b6037]" : "border-stone-300"}`}>{split === id && <Check size={10} className="text-white" />}</span><div><p className="text-[11px] font-semibold">{title}</p><p className="mt-0.5 text-[9px] text-stone-400">{detail}</p></div></div></button>)}</div>{split === "equal" && <div className="mt-4 rounded-xl bg-[#261d18] p-4 text-white"><p className="text-[9px] text-stone-400">{selected.guests} partes de</p><p className="mt-1 text-2xl font-bold">{money(perPerson)}</p></div>}</Card><Button onClick={() => setPaymentOpen(true)} disabled={remaining <= 0} className="w-full min-h-12"><WalletCards size={17} />Registrar pago</Button></div>
      </div>
    </div>
    <Modal open={paymentOpen} onClose={() => setPaymentOpen(false)} title="Registrar pago" description={`Mesa ${selected.table} · Saldo ${money(remaining)}`}><div><p className="mb-3 text-xs font-semibold text-stone-600">Medio de pago</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Efectivo", Banknote], ["Tarjeta", CreditCard], ["Transferencia", CircleDollarSign], ["QR", QrCode]].map(([name, Icon]) => <button key={String(name)} onClick={() => setMethod(String(name))} className={`rounded-2xl border p-4 text-center transition ${method === name ? "border-[#b77843] bg-[#f4e7dc] text-[#8b522e]" : "border-stone-200 bg-white text-stone-500"}`}><Icon size={20} className="mx-auto" /><p className="mt-2 text-[10px] font-semibold">{String(name)}</p></button>)}</div><div className="mt-5 rounded-2xl bg-stone-100 p-4"><div className="flex justify-between"><span className="text-xs text-stone-500">Monto a registrar</span><strong className="text-lg">{money(remaining)}</strong></div></div><Button onClick={pay} className="mt-5 w-full min-h-12"><Check size={16} />Confirmar pago con {method}</Button><p className="mt-3 text-center text-[9px] text-stone-400">Al completar el saldo, la mesa pasará automáticamente a limpieza.</p></div></Modal>
  </div>;
}
