"use client";

import { useState } from "react";
import { Check, ChevronDown, Minus, Plus, Search, Send, ShoppingBag, UserRound, X } from "lucide-react";
import { menuSeed } from "@/lib/data";
import type { MenuItem, OrderItem } from "@/lib/types";
import { cn, money } from "@/lib/utils";
import { useOperations } from "../operations-provider";
import { Button, Card, PageHeader, StatusBadge } from "../ui";

type CartItem = MenuItem & { quantity: number };

export function OrdersView() {
  const { tables, addOrder } = useOperations();
  const activeTables = tables.filter((table) => table.guests > 0);
  const [table, setTable] = useState(activeTables[0]?.number ?? 1);
  const [category, setCategory] = useState("Todos");
  const [search, setSearch] = useState("");
  const [cart, setCart] = useState<CartItem[]>([]);
  const categories = ["Todos", ...Array.from(new Set(menuSeed.map((item) => item.category)))];
  const filtered = menuSeed.filter((item) => (category === "Todos" || item.category === category) && item.name.toLowerCase().includes(search.toLowerCase()));
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const guestCount = tables.find((item) => item.number === table)?.guests ?? 1;
  function add(item: MenuItem) { if (item.availability === "No disponible") return; setCart((current) => { const existing = current.find((line) => line.id === item.id); return existing ? current.map((line) => line.id === item.id ? { ...line, quantity: line.quantity + 1 } : line) : [...current, { ...item, quantity: 1 }]; }); }
  function quantity(id: number, delta: number) { setCart((current) => current.map((item) => item.id === id ? { ...item, quantity: item.quantity + delta } : item).filter((item) => item.quantity > 0)); }
  function send() { const items: OrderItem[] = cart.map(({ name, quantity: qty, price }) => ({ name, quantity: qty, price })); addOrder(table, items); setCart([]); }
  return <div className="space-y-6"><PageHeader eyebrow="Pedido digital" title="Tomar pedido" description="Productos grandes, contexto de mesa visible y envío directo a cocina." actions={<div className="relative"><select value={table} onChange={(event) => { setTable(Number(event.target.value)); setCart([]); }} className="h-11 appearance-none rounded-xl border border-stone-200 bg-white pl-4 pr-10 text-sm font-semibold outline-none"><option disabled>Seleccionar mesa</option>{activeTables.map((item) => <option key={item.number} value={item.number}>Mesa {item.number} · {item.guests} personas</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-stone-400" /></div>} />
    <div className="grid gap-5 xl:grid-cols-[1fr_370px]">
      <div className="min-w-0 space-y-4"><Card className="p-3"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3.5 top-3 text-stone-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar plato o bebida" className="h-10 w-full rounded-xl bg-stone-100 pl-10 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#b77843]/20" /></div><div className="scrollbar-none flex max-w-full gap-1 overflow-auto">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn("whitespace-nowrap rounded-xl px-3 py-2 text-[11px] font-semibold", category === item ? "bg-[#211a16] text-white" : "text-stone-500 hover:bg-stone-100")}>{item}</button>)}</div></div></Card>
        <div className="grid grid-cols-2 gap-3 md:grid-cols-3">{filtered.map((item, index) => <button key={item.id} onClick={() => add(item)} disabled={item.availability === "No disponible"} className="group relative min-h-[184px] overflow-hidden rounded-[20px] border border-stone-200 bg-white p-4 text-left transition hover:-translate-y-0.5 hover:border-[#d0ad8e] hover:shadow-md disabled:opacity-50"><div className={`absolute right-0 top-0 h-24 w-24 rounded-bl-full opacity-70 ${["bg-[#ecd8c5]", "bg-[#dfc4ac]", "bg-[#e8d1bd]"][index % 3]}`} /><div className="relative"><div className="mb-8 flex items-start justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#2b211b] font-serif text-lg text-[#dda26e]">{item.name.charAt(0)}</span>{item.popular && <StatusBadge tone="copper">Popular</StatusBadge>}</div><h3 className="text-sm font-semibold leading-5">{item.name}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-stone-500">{item.description}</p><div className="mt-3 flex items-center justify-between"><span className="text-sm font-bold">{money(item.price)}</span><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-stone-100 text-stone-600 transition group-hover:bg-[#211a16] group-hover:text-white"><Plus size={14} /></span></div>{item.availability === "Poco stock" && <p className="mt-2 text-[9px] font-semibold text-amber-700">Últimas unidades</p>}</div></button>)}</div>
      </div>
      <Card className="h-fit overflow-hidden xl:sticky xl:top-24"><div className="border-b border-stone-100 p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#9b6037]">Pedido actual</p><h2 className="mt-1 font-serif text-2xl">Mesa {table}</h2></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f1e6db] text-[#9b6037]"><ShoppingBag size={18} /></span></div><div className="mt-4 flex items-center gap-2 text-[10px] text-stone-500"><UserRound size={13} />{guestCount} personas<span className="ml-auto">Atiende {tables.find((item) => item.number === table)?.waiter}</span></div></div>
        <div className="max-h-[360px] min-h-[220px] overflow-auto p-4">{cart.length === 0 ? <div className="flex min-h-[190px] flex-col items-center justify-center text-center"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-stone-100 text-stone-400"><ShoppingBag size={20} /></span><p className="mt-4 text-sm font-semibold">El pedido está vacío</p><p className="mt-1 max-w-[220px] text-[10px] leading-4 text-stone-400">Seleccioná productos del menú para comenzar.</p></div> : <div className="space-y-3">{cart.map((item) => <div key={item.id} className="rounded-2xl bg-stone-50 p-3"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold">{item.name}</p><p className="mt-1 text-[10px] text-stone-400">{money(item.price)} c/u</p></div><button onClick={() => quantity(item.id, -item.quantity)} className="text-stone-400 hover:text-rose-600"><X size={14} /></button></div><div className="mt-3 flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={() => quantity(item.id, -1)} className="flex h-7 w-7 items-center justify-center rounded-lg border border-stone-200 bg-white"><Minus size={12} /></button><span className="w-4 text-center text-xs font-bold">{item.quantity}</span><button onClick={() => quantity(item.id, 1)} className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#211a16] text-white"><Plus size={12} /></button></div><p className="text-xs font-bold">{money(item.price * item.quantity)}</p></div></div>)}</div>}</div>
        <div className="border-t border-stone-100 bg-stone-50/70 p-5"><div className="mb-4 flex items-center justify-between"><span className="text-xs text-stone-500">Total estimado</span><span className="text-xl font-bold tracking-tight">{money(total)}</span></div><Button onClick={send} disabled={cart.length === 0} className="w-full"><Send size={15} />Confirmar y enviar a cocina</Button>{cart.length > 0 && <p className="mt-3 flex items-center justify-center gap-1 text-[9px] text-stone-400"><Check size={11} />Se enviará en tiempo real</p>}</div>
      </Card>
    </div>
  </div>;
}
