"use client";

import { FormEvent, useState } from "react";
import { Check, Clock3, Phone, Plus, Search, Sparkles, UsersRound } from "lucide-react";
import { cn } from "@/lib/utils";
import { useOperations } from "../operations-provider";
import { Button, Card, Field, inputClass, Modal, PageHeader, StatusBadge } from "../ui";

const reservationTone = { Confirmada: "success", Pendiente: "warning", Presente: "copper", Cancelada: "neutral" } as const;

export function ReservationsView() {
  const { reservations, addReservation } = useOperations();
  const [open, setOpen] = useState(false);
  const [filter, setFilter] = useState("Todas");
  const visible = filter === "Todas" ? reservations : reservations.filter((item) => item.status === filter);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); addReservation({ name: String(data.get("name")), phone: String(data.get("phone")), time: String(data.get("time")), guests: Number(data.get("guests")), preference: String(data.get("preference")), table: undefined }); setOpen(false); }
  return <div className="space-y-6"><PageHeader eyebrow="Recepción" title="Reservas de hoy" description="Confirmaciones, llegadas y disponibilidad futura en una misma vista." actions={<Button onClick={() => setOpen(true)}><Plus size={15} />Nueva reserva</Button>} />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Reservas", reservations.length, "bg-[#241b16] text-white"], ["Confirmadas", reservations.filter(r => r.status === "Confirmada").length, "bg-white"], ["Personas", reservations.reduce((s,r) => s+r.guests,0), "bg-white"], ["Pendientes", reservations.filter(r => r.status === "Pendiente").length, "bg-amber-50 border-amber-200"]].map(([label,value,style]) => <div key={String(label)} className={`rounded-2xl border border-stone-200 p-4 ${style}`}><p className="text-[10px] opacity-55">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></div>)}</div>
    <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-stone-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="scrollbar-none flex gap-1 overflow-x-auto">{["Todas", "Confirmada", "Pendiente", "Presente"].map((item) => <button key={item} onClick={() => setFilter(item)} className={cn("rounded-xl px-3 py-2 text-[11px] font-semibold", filter === item ? "bg-[#211a16] text-white" : "text-stone-500 hover:bg-stone-100")}>{item}</button>)}</div><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-stone-400" /><input placeholder="Buscar reserva" className="h-9 rounded-xl bg-stone-100 pl-9 pr-3 text-xs outline-none" /></div></div><div className="divide-y divide-stone-100">{visible.map((reservation) => <div key={reservation.id} className="grid gap-4 p-4 transition hover:bg-stone-50/70 sm:grid-cols-[70px_1fr_auto] sm:items-center md:p-5"><div><p className="font-serif text-2xl">{reservation.time}</p><p className="mt-1 text-[9px] text-stone-400">HOY</p></div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{reservation.name}</p><StatusBadge tone={reservationTone[reservation.status]}>{reservation.status}</StatusBadge></div><div className="mt-2 flex flex-wrap gap-4 text-[10px] text-stone-500"><span className="flex items-center gap-1"><UsersRound size={12} />{reservation.guests} personas</span><span className="flex items-center gap-1"><Phone size={12} />{reservation.phone}</span><span>{reservation.preference}</span></div></div><div className="flex items-center gap-2">{reservation.table && <span className="rounded-xl bg-[#f1e5da] px-3 py-2 text-xs font-semibold text-[#87512e]">Mesa {reservation.table}</span>}<button className="rounded-xl border border-stone-200 bg-white px-3 py-2 text-xs font-semibold text-stone-500">Ver detalle</button></div></div>)}</div></Card>
    <Modal open={open} onClose={() => setOpen(false)} title="Nueva reserva" description="Se guardará inicialmente como pendiente."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Nombre"><input required name="name" placeholder="Nombre y apellido" className={inputClass} /></Field><Field label="Teléfono"><input required name="phone" placeholder="11 0000-0000" className={inputClass} /></Field><Field label="Hora"><input required name="time" type="time" defaultValue="21:30" className={inputClass} /></Field><Field label="Personas"><input required name="guests" type="number" min="1" max="20" defaultValue="2" className={inputClass} /></Field><Field label="Preferencia"><select name="preference" className={inputClass}><option>Sin preferencia</option><option>Ventanal</option><option>Terraza</option><option>Accesibilidad</option><option>Silla para bebé</option></select></Field><div className="flex items-end"><Button className="w-full" type="submit">Crear reserva</Button></div></form></Modal>
  </div>;
}

export function WaitlistView() {
  const { waitlist, seatWaitlist, addWaitlist } = useOperations();
  const [open, setOpen] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); addWaitlist({ name: String(data.get("name")), phone: String(data.get("phone")), guests: Number(data.get("guests")), preference: String(data.get("preference")) }); setOpen(false); }
  return <div className="space-y-6"><PageHeader eyebrow="Recepción" title="Lista de espera" description="Priorizá por llegada y compatibilidad, no solo por disponibilidad." actions={<Button onClick={() => setOpen(true)}><Plus size={15} />Agregar grupo</Button>} />
    {waitlist.some((entry) => entry.recommendation) && <div className="flex flex-col gap-4 rounded-[22px] border border-[#ddc0a5] bg-[#f5e8dc] p-5 sm:flex-row sm:items-center"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#a5663b] text-white"><Sparkles size={19} /></span><div className="flex-1"><p className="text-sm font-semibold text-[#6f4327]">Hay una mesa compatible disponible</p><p className="mt-1 text-xs text-[#936345]">Grupo {waitlist.find((entry) => entry.recommendation)?.name} · Mesa {waitlist.find((entry) => entry.recommendation)?.recommendation} aprovecha mejor la capacidad.</p></div><StatusBadge tone="copper">Recomendación activa</StatusBadge></div>}
    <Card className="overflow-hidden"><div className="border-b border-stone-100 p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Grupos esperando</h2><p className="mt-1 text-[10px] text-stone-400">Tiempo promedio estimado: 21 minutos</p></div><span className="flex h-9 min-w-9 items-center justify-center rounded-xl bg-[#241b16] text-sm font-semibold text-white">{waitlist.length}</span></div></div><div className="divide-y divide-stone-100">{waitlist.map((entry, index) => <div key={entry.id} className="grid gap-4 p-4 sm:grid-cols-[50px_1fr_auto] sm:items-center md:p-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-stone-100 font-serif text-xl">{index + 1}</div><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">Grupo {entry.name}</p><StatusBadge tone={entry.wait > 25 ? "warning" : "neutral"}>{entry.wait} min</StatusBadge></div><div className="mt-2 flex flex-wrap gap-4 text-[10px] text-stone-500"><span className="flex items-center gap-1"><UsersRound size={12} />{entry.guests} personas</span><span className="flex items-center gap-1"><Clock3 size={12} />Llegó {entry.arrivedAt}</span><span>{entry.preference}</span></div></div><div className="flex flex-col items-stretch gap-2 sm:items-end">{entry.recommendation ? <><p className="text-[10px] font-semibold text-[#8f552f]">Mesa {entry.recommendation} recomendada</p><Button onClick={() => seatWaitlist(entry.id)} className="h-9 min-h-9 px-3"><Check size={14} />Asignar mesa</Button></> : <span className="rounded-xl bg-stone-100 px-3 py-2 text-[10px] font-medium text-stone-500">Buscando mesa compatible</span>}</div></div>)}</div>{waitlist.length === 0 && <div className="p-12 text-center"><Check className="mx-auto text-emerald-600" /><p className="mt-3 text-sm font-semibold">No hay grupos esperando</p></div>}</Card>
    <Modal open={open} onClose={() => setOpen(false)} title="Agregar a la lista" description="El sistema buscará la mesa compatible más eficiente."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Apellido o grupo"><input required name="name" placeholder="Ej. Fernández" className={inputClass} /></Field><Field label="Teléfono"><input required name="phone" placeholder="11 0000-0000" className={inputClass} /></Field><Field label="Personas"><input required name="guests" type="number" min="1" max="20" defaultValue="2" className={inputClass} /></Field><Field label="Preferencia"><select name="preference" className={inputClass}><option>Sin preferencia</option><option>Ventanal</option><option>Terraza</option><option>Accesibilidad</option><option>Silla para bebé</option></select></Field><div className="sm:col-span-2"><Button type="submit" className="w-full">Agregar y buscar mesa</Button></div></form></Modal>
  </div>;
}
