"use client";

import Image from "next/image";
import Link from "next/link";
import { motion, useScroll, useTransform } from "framer-motion";
import {
  ArrowRight, BarChart3, CalendarCheck, Check, ChefHat, ChevronRight,
  CircleDollarSign, Clock3, Menu, PackageCheck, Play, TableProperties, X,
} from "lucide-react";
import { useState } from "react";

const modules = [
  { icon: TableProperties, title: "Gestión de mesas", text: "Disponibilidad, ocupación y responsable en tiempo real.", metric: "+18%", detail: "rotación" },
  { icon: ChefHat, title: "Pedidos digitales", text: "Del salón a cocina sin papeles, dudas ni pedidos perdidos.", metric: "−32%", detail: "demoras" },
  { icon: CalendarCheck, title: "Reservas", text: "Confirmaciones, lista de espera y asignación inteligente.", metric: "2.4×", detail: "más claridad" },
  { icon: CircleDollarSign, title: "Caja y pagos", text: "Cuentas divididas y pagos mixtos, sin frenar el servicio.", metric: "3 min", detail: "ahorrados" },
  { icon: PackageCheck, title: "Inventario", text: "Stock, vencimientos y recetas conectados con cada venta.", metric: "−21%", detail: "desperdicio" },
  { icon: BarChart3, title: "Control del negocio", text: "El rendimiento del local, explicado en segundos.", metric: "100%", detail: "visible" },
];

const problems = ["Pedidos que se pierden", "Clientes esperando sin información", "Mozos sobrecargados", "Cocina interrumpida", "Cuentas difíciles de dividir", "Productos que se terminan"];

function ProductMockup() {
  return <motion.div initial={{ opacity: 0, y: 30, rotateX: 4 }} animate={{ opacity: 1, y: 0, rotateX: 0 }} transition={{ delay: .35, duration: .8 }} className="relative mx-auto mt-14 w-full max-w-6xl px-3 lg:mt-[-40px] lg:translate-y-[42%]">
    <div className="overflow-hidden rounded-[20px] border border-white/15 bg-[#f6f4f0] shadow-[0_50px_140px_rgba(0,0,0,.55)] ring-1 ring-black/20">
      <div className="flex h-10 items-center border-b border-stone-200 bg-[#ede9e3] px-4"><div className="flex gap-1.5"><span className="h-2.5 w-2.5 rounded-full bg-[#c56f60]" /><span className="h-2.5 w-2.5 rounded-full bg-[#d9ad5d]" /><span className="h-2.5 w-2.5 rounded-full bg-[#6fa477]" /></div><div className="mx-auto rounded-md bg-white/70 px-20 py-1 text-[8px] text-stone-400">operations.kansas.ar</div></div>
      <div className="grid min-h-[330px] grid-cols-[74px_1fr] md:grid-cols-[180px_1fr]">
        <div className="bg-[#191512] p-3 md:p-4"><div className="mb-8 flex h-8 w-8 items-center justify-center rounded-lg border border-white/10 font-serif text-[#dfa46f]">K</div>{["Resumen", "Mesas", "Pedidos", "Cocina", "Reservas"].map((item, index) => <div key={item} className={`mb-2 flex h-8 items-center rounded-lg px-2 text-[9px] ${index === 0 ? "bg-white/10 text-white" : "text-stone-600"}`}><span className="mr-2 h-2 w-2 rounded-sm bg-current" /><span className="hidden md:block">{item}</span></div>)}</div>
        <div className="p-4 md:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-widest text-[#a3673d]">Servicio en vivo</p><p className="mt-1 font-serif text-lg text-stone-800 md:text-2xl">Buenas noches, Palermo.</p></div><div className="rounded-lg bg-emerald-50 px-2 py-1 text-[8px] text-emerald-700">● En tiempo real</div></div>
          <div className="mt-5 grid grid-cols-2 gap-2 md:grid-cols-4">{[["Ocupación", "78%"], ["Clientes", "86"], ["En cocina", "12"], ["Ventas", "$4,8M"]].map(([l,v], i) => <div key={l} className={`${i === 0 ? "bg-[#281e18] text-white" : "border border-stone-200 bg-white"} rounded-xl p-3`}><p className="text-[8px] opacity-50">{l}</p><p className="mt-2 text-base font-semibold md:text-xl">{v}</p></div>)}</div>
          <div className="mt-3 grid gap-3 md:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-stone-200 bg-white p-4"><div className="flex justify-between text-[8px]"><span className="font-semibold">Actividad del salón</span><span className="text-stone-400">Ahora</span></div><div className="mt-4 flex h-24 items-end gap-1.5">{[30,48,40,68,56,82,74,92,66,78,88,72,96,84].map((height, i) => <span key={i} style={{ height: `${height}%` }} className={`flex-1 rounded-t-sm ${i > 10 ? "bg-[#b77843]" : "bg-[#eaded2]"}`} />)}</div></div><div className="rounded-xl border border-stone-200 bg-white p-4"><p className="text-[8px] font-semibold">Atención requerida</p><div className="mt-3 space-y-2">{[["Mesa 7", "Solicitó cuenta"], ["Mesa 3", "Espera pedido"], ["K-184", "Demorado"]].map(([a,b], i) => <div key={a} className="flex items-center gap-2 rounded-lg bg-stone-50 p-2"><span className={`h-2 w-2 rounded-full ${i === 2 ? "bg-rose-500" : "bg-amber-500"}`} /><span className="text-[8px] font-semibold">{a}</span><span className="ml-auto text-[7px] text-stone-400">{b}</span></div>)}</div></div></div>
        </div>
      </div>
    </div>
  </motion.div>;
}

export function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { scrollYProgress } = useScroll();
  const y = useTransform(scrollYProgress, [0, .4], [0, 110]);
  return <div className="overflow-hidden bg-[#f4efe8] text-[#211a16]">
    <section className="noise relative min-h-[920px] overflow-hidden bg-[#171311] text-white lg:min-h-[980px]">
      <motion.div style={{ y }} className="absolute inset-0"><Image src="/images/kansas-hero.png" alt="Restaurante contemporáneo con iluminación cálida" fill priority className="object-cover object-[62%_center] opacity-65" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(18,14,12,.98)_0%,rgba(18,14,12,.83)_34%,rgba(18,14,12,.2)_72%,rgba(18,14,12,.45)_100%)]" /><div className="hero-grid absolute inset-0 opacity-25" /></motion.div>
      <header className="relative z-20 mx-auto flex h-24 max-w-[1380px] items-center px-5 md:px-10">
        <Link href="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full border border-white/30 font-serif text-2xl">K</span><span><span className="block font-serif text-xl tracking-[.12em]">KANSAS</span><span className="block text-[8px] uppercase tracking-[.28em] text-[#d49a68]">Operations</span></span></Link>
        <nav className="ml-auto hidden items-center gap-8 text-xs font-medium text-stone-300 lg:flex"><a href="#solucion" className="hover:text-white">Producto</a><a href="#beneficios" className="hover:text-white">Beneficios</a><a href="#experiencia" className="hover:text-white">Experiencia</a><Link href="/login" className="hover:text-white">Ingresar</Link><Link href="/login" className="rounded-full bg-[#c48551] px-5 py-3 font-semibold text-white transition hover:bg-[#d6945e]">Solicitar demo</Link></nav>
        <button onClick={() => setMenuOpen(!menuOpen)} className="ml-auto rounded-xl border border-white/15 p-2 lg:hidden" aria-label="Abrir menú">{menuOpen ? <X /> : <Menu />}</button>
        {menuOpen && <div className="absolute left-5 right-5 top-20 rounded-2xl border border-white/10 bg-[#251c17] p-4 shadow-2xl lg:hidden"><a onClick={() => setMenuOpen(false)} href="#solucion" className="block rounded-xl px-3 py-3 text-sm text-stone-300">Producto</a><a onClick={() => setMenuOpen(false)} href="#beneficios" className="block rounded-xl px-3 py-3 text-sm text-stone-300">Beneficios</a><Link href="/login" className="mt-2 block rounded-xl bg-[#c48551] px-4 py-3 text-center text-sm font-semibold">Solicitar demo</Link></div>}
      </header>
      <div className="relative z-10 mx-auto max-w-[1380px] px-5 pb-40 pt-24 md:px-10 md:pt-32 lg:pb-64 lg:pt-36">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }} className="max-w-3xl">
          <div className="mb-7 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.06] px-3 py-2 text-[10px] font-semibold uppercase tracking-[.18em] text-[#ddb082]"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-[#ddb082]" />La operación, a la altura de la experiencia</div>
          <h1 className="font-serif text-[50px] leading-[.97] tracking-[-.055em] sm:text-6xl md:text-[78px] lg:text-[88px]">Menos espera.<br /><span className="italic text-[#d6a276]">Menos errores.</span><br />Más mesas atendidas.</h1>
          <p className="mt-7 max-w-xl text-base leading-7 text-stone-300 md:text-lg">Gestioná mesas, pedidos, cocina, reservas, pagos e inventario desde una sola plataforma diseñada para el ritmo real del restaurante.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="group inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-[#c48551] px-7 text-sm font-semibold transition hover:bg-[#d69561]">Solicitar demo <ArrowRight size={16} className="transition group-hover:translate-x-1" /></Link><a href="#experiencia" className="inline-flex min-h-13 items-center justify-center gap-3 rounded-full border border-white/20 bg-white/[.04] px-7 text-sm font-semibold backdrop-blur-sm transition hover:bg-white/10"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-white text-stone-900"><Play size={11} fill="currentColor" /></span>Ver cómo funciona</a></div>
          <div className="mt-11 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/10 pt-6 text-[11px] text-stone-400">{["Información en tiempo real", "Listo para tablets", "Roles y permisos"].map((item) => <span key={item} className="flex items-center gap-2"><Check size={13} className="text-[#d69b68]" />{item}</span>)}</div>
        </motion.div>
      </div>
      <ProductMockup />
    </section>

    <section className="px-5 pb-28 pt-44 md:px-10 md:pt-56 lg:pt-72" id="experiencia"><div className="mx-auto max-w-[1280px]"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#9b6037]">El desafío diario</p><h2 className="mt-4 max-w-xl font-serif text-4xl leading-[1.04] tracking-[-.04em] md:text-6xl">Administrar un restaurante no debería ser un caos.</h2></div><div><p className="max-w-xl text-base leading-7 text-stone-600">Durante un servicio lleno, cada minuto cuenta. Cuando la información vive en papeles, memoria y sistemas separados, la experiencia del cliente se resiente.</p><div className="mt-7 grid gap-x-8 gap-y-4 sm:grid-cols-2">{problems.map((problem, index) => <motion.div initial={{ opacity: 0, x: 15 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} transition={{ delay: index * .05 }} key={problem} className="flex items-center gap-3 border-b border-stone-300/70 pb-3 text-sm font-medium"><span className="font-serif text-xl text-[#b77843]">0{index + 1}</span>{problem}</motion.div>)}</div></div></div></div></section>

    <section id="solucion" className="relative bg-[#211a16] px-5 py-28 text-white md:px-10"><div className="absolute inset-0 hero-grid opacity-10" /><div className="relative mx-auto max-w-[1280px]"><div className="max-w-2xl"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#d99d6b]">Una sola operación</p><h2 className="mt-4 font-serif text-4xl tracking-[-.04em] md:text-6xl">Todo tu restaurante conectado.</h2><p className="mt-5 max-w-xl leading-7 text-stone-400">Cada equipo ve lo que necesita, en el momento exacto. Sin perder la calidez de un servicio personal.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[28px] border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{modules.map(({ icon: Icon, title, text, metric, detail }, index) => <motion.div key={title} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-80px" }} transition={{ delay: index * .06 }} className="group bg-[#211a16] p-7 transition hover:bg-[#2b211b]"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/[.06] text-[#d49a68] transition group-hover:bg-[#c48551] group-hover:text-white"><Icon size={20} /></span><span className="text-right"><strong className="block font-serif text-2xl text-[#d49a68]">{metric}</strong><span className="text-[9px] uppercase tracking-wider text-stone-600">{detail}</span></span></div><h3 className="mt-8 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-400">{text}</p><span className="mt-6 inline-flex items-center gap-1 text-xs font-semibold text-stone-500 transition group-hover:text-[#d49a68]">Conocer más <ChevronRight size={13} /></span></motion.div>)}</div></div></section>

    <section id="beneficios" className="px-5 py-28 md:px-10"><div className="mx-auto grid max-w-[1280px] gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative min-h-[520px] overflow-hidden rounded-[32px] bg-[#2b211b]"><Image src="/images/kansas-hero.png" alt="Plato y salón Kansas" fill className="object-cover object-[70%_center]" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-white/15 bg-black/30 p-5 text-white backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#e0a978]">Servicio de hoy</p><p className="mt-2 font-serif text-3xl">94% a tiempo</p></div><Clock3 className="text-[#e0a978]" size={30} /></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[94%] rounded-full bg-[#d3915c]" /></div></div></div><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#9b6037]">Tecnología que no interrumpe</p><h2 className="mt-4 font-serif text-4xl leading-[1.06] tracking-[-.04em] md:text-6xl">Diseñada para trabajar bajo presión.</h2><p className="mt-6 max-w-xl text-base leading-7 text-stone-600">Acciones grandes, estados que se entienden de un vistazo y el contexto importante siempre visible. La interfaz acompaña al equipo sin competir por su atención.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{["1–3 interacciones por acción", "Actualización en tiempo real", "Asignación inteligente", "Información por rol", "Alertas accionables", "Tablet y escritorio"].map((item) => <div key={item} className="flex items-center gap-3 text-sm font-semibold text-stone-700"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-[#e8d5c3] text-[#9a6038]"><Check size={13} /></span>{item}</div>)}</div><Link href="/login" className="mt-10 inline-flex items-center gap-2 rounded-full bg-[#211a16] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#3b2b22]">Explorar la plataforma <ArrowRight size={15} /></Link></div></div></section>

    <section className="px-5 pb-20 md:px-10"><div className="noise relative mx-auto max-w-[1280px] overflow-hidden rounded-[36px] bg-[#1c1714] px-6 py-20 text-center text-white md:px-12"><div className="absolute left-1/2 top-0 h-64 w-96 -translate-x-1/2 rounded-full bg-[#b77843]/20 blur-[100px]" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#d9a06f]">El próximo servicio empieza acá</p><h2 className="mx-auto mt-5 max-w-3xl font-serif text-4xl tracking-[-.04em] md:text-6xl">Tu restaurante puede funcionar mejor.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-6 text-stone-400 md:text-base">Centralizá la operación de tu restaurante y mantené a todo tu equipo conectado en tiempo real.</p><Link href="/login" className="mt-9 inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-[#c48551] px-7 text-sm font-semibold transition hover:bg-[#d69561]">Solicitar una demostración <ArrowRight size={16} /></Link></div></div></section>

    <footer className="border-t border-stone-300/70 px-5 py-10 md:px-10"><div className="mx-auto flex max-w-[1280px] flex-col items-center justify-between gap-5 text-center md:flex-row md:text-left"><div><p className="font-serif text-xl tracking-[.12em]">KANSAS <span className="text-[#9b6037]">OPERATIONS</span></p><p className="mt-1 text-[10px] text-stone-500">Contemporary American hospitality, connected.</p></div><p className="text-xs text-stone-500">Concepto digital para Kansas Grill & Bar · 2026</p></div></footer>
  </div>;
}
